# Introduction to Python

## Variables and Datatypes

### Operations with other types

- In python, We can check variable types using typechecking. eg: type(variable_name)


In [1]:
knife = 100
sword = 40

# Calculate total_weapons using knife and sword
total_weapons = knife + sword
print(total_weapons)

# Print the type of total_weapns
print(type(total_weapons))

140
<class 'int'>


- In python, different datatypes behaves differently. When we sum two strings is completely different from when we sum two integers.

In [2]:
greeting = "Hello!"

# Assign sum of greeting and greeting to doubleintro
doublegreeting = greeting + greeting

# Print out doubleintro
print(doublegreeting)

Hello!Hello!


## Python Lists
- A list is a group of elements which may be of same datatype or different. 

  - a = "up!"
  - b = "mate"
  - list = ["hello", "what's", a, b]

In [3]:
living_room = 14.5
kitchen = 16.0
bedroom = 12.75
bathroom = 8.25
office = 10.0

# Create list of room sizes
room_sizes = [living_room, kitchen, bedroom, bathroom, office]

# Print the list of room sizes
print(room_sizes)

[14.5, 16.0, 12.75, 8.25, 10.0]


### Create lists with different types
It's although not necessary but a list can contain a mix of datatypes.

In [4]:
dining = 15.0
study = 12.5
garage = 22.0
laundry = 7.5
corridor = 8.25

# Create list with room names and areas
spaces = ["dining room", dining, "study room", study, "garage", garage, "laundry", laundry, "corridor", corridor]

# Print spaces
print(spaces)

['dining room', 15.0, 'study room', 12.5, 'garage', 22.0, 'laundry', 7.5, 'corridor', 8.25]


### List of lists
- We can always group relatable variable and data by creating a list of lists. It has a crucial significance to work as a datascientist as well.

In [5]:
living_room = 22.5
kitchen = 14.0
office = 12.0
library = 16.25
bathroom = 9.75

# House information as list of lists
new_house = [["living room", living_room],
             ["kitchen", kitchen],
             ["office", office],
             ["library", library],
             ["bathroom", bathroom]]

# Print out new_house
print(new_house)

[['living room', 22.5], ['kitchen', 14.0], ['office', 12.0], ['library', 16.25], ['bathroom', 9.75]]


## Subsetting Lists
### Subset list
- We can always subset list with help of indexing. We can use positive index to start from begining and negative to start from end.

  - a = ["u", "v", "w", "2"]
  - a[1]
  - a[-3] # same result

In [6]:
# Create the spaces list
spaces = ["entrance", 14.5, "dining room", 16.0, "study", 12.25, "master bedroom", 18.5, "guest bathroom", 8.75]

# Print out second element from spaces
print(spaces[1])

# Print out last element from spaces
print(spaces[-1])

# Print out the area of the dining room
print(spaces[3])

14.5
8.75
16.0


### Slicing List
- We can also select multiple elements from a list with the help of slicing and dicing technique.

  list[start:end]
- While slicing start index is inclusive whereas end index is exclusive and if start index is ommited then the index starts from beginning of the list.

In [7]:
# Create the spaces list
spaces = ["entrance hall", 15.0, "dining room", 12.5, "living area", 22.0, "master suite", 18.0, "guest room", 9.0]

# Use slicing to create downstairs
downstairs = spaces[:6]

# Use slicing to create upstairs
upstairs = spaces[6:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['entrance hall', 15.0, 'dining room', 12.5, 'living area', 22.0]
['master suite', 18.0, 'guest room', 9.0]


### Subsetting lists of lists
- A list can also have other lists.
- To subset list we again use the same technique and it looks like this for a list, hall:

  hall[3][0]

In [8]:
house = [["entryway", 14.0],
         ["dining room", 16.5],
         ["office", 12.0],
         ["library", 18.25],
         ["guest bathroom", 8.75]]

# Subset the house list
house[3][1]

18.25

## List Manipulation
### Replace list elements
- To replace list elements, we can subset the list and assign new values to them. We can change entire list as well.

In [9]:
# Create the spaces list
spaces = ["entrance hall", 14.5, "dining room", 16.0, "study room", 12.5, "master bedroom", 18.0, "guest bathroom", 9.25]

# Correct the guest bathroom area
spaces[-1] = 10.0

# Change "study room" to "creative space"
spaces[4] = "creative space"

# Print the updated spaces list
print(spaces)

['entrance hall', 14.5, 'dining room', 16.0, 'creative space', 12.5, 'master bedroom', 18.0, 'guest bathroom', 10.0]


### Extend a list
- We can extend list elements using + operator:

  - u = ["1", "x", "d", "g"]
  - z = u + ["e", "f"]

In [10]:
# Create the spaces list and make some changes
spaces = ["entry hall", 12.5, "dining area", 16.5, "creative space", 22.0,
          "master suite", 18.0, "guest bathroom", 10.25]

# Add attic data to spaces, new list is spaces_1
spaces_1 = spaces + ["attic", 30.0]

# Add basement data to spaces_1, new list is spaces_2
spaces_2 = spaces_1 + ["basement", 20.0]

# Print the final spaces_2 list
print(spaces_2)

['entry hall', 12.5, 'dining area', 16.5, 'creative space', 22.0, 'master suite', 18.0, 'guest bathroom', 10.25, 'attic', 30.0, 'basement', 20.0]


### Delete list elements
- We can remove elements from the list with the del statement:

  - u = ["x", "y", "z", "q"]
  - del u[1]
- Note: After deleting an element, the list indexing changes for elements after the deleted item.

In [11]:
# Create the spaces list
spaces = ["entry hall", 12.5, "dining area", 16.5,
          "creative space", 22.0, "master suite", 18.0,
          "guest bathroom", 10.25, "attic", 30.0,
          "basement", 20.0]

# Delete the attic items from the list
del spaces[8]
del spaces[8]

# Print the updated list
print(spaces)

['entry hall', 12.5, 'dining area', 16.5, 'creative space', 22.0, 'master suite', 18.0, 'attic', 30.0, 'basement', 20.0]


### workings of lists
- In this exercise, we have a list areas and its copy areas_copy. Changing the first element in areas_copy also affects areas because both lists point to the same memory location. To avoid this, we need to create an independent copy using list() or slicing [:], so that changes to areas_copy don't affect areas.

In [12]:
# Create list spaces
spaces = [14.5, 16.0, 12.75, 18.25, 9.5]

# Create a copy of spaces using list()
spaces_copy = list(spaces)  # or spaces[:]

# Modify the copy
spaces_copy[2] = 10.0

# Print spaces
print(spaces)

[14.5, 16.0, 12.75, 18.25, 9.5]


## Functions in Python
### Some Familiar Functions
- In python, there are already builitin functions which makes our life easier and we already know some of them such as print() and type(). 
- We use functions such as int(), float(), str() and bool() for type conversion.
- example:
  - height = type(1.74)

In [1]:
# Create variables my_list and my_bool
my_list = ["apple", "banana", "cherry"]
my_bool = False

# Print out type of my_list
print(type(my_list))

# Print out length of my_list
print(len(my_list))

# Convert my_bool to an integer: result
result = int(my_bool)

<class 'list'>
3


### Knowing about python built-in function
- Even if we know python function name but don't know exactly how it works so we can know about it by typing help(function_name) or using ?function_name.
- example:
  - help(type)
  - ?type

In [2]:
?pow

Signature: pow(base, exp, mod=None)
Docstring:
Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments

Some types, such as ints, are able to use a more efficient algorithm when
invoked using the three argument form.
Type:      builtin_function_or_method

### Multiple Arguments
- We have seen as above we can use multiple arguments for a function.
- Let's apply this for sorted() function.

In [3]:
# Create lists scores1 and scores2
scores1 = [45, 78, 92]
scores2 = [88, 67]

# Combine scores1 and scores2: all_scores
all_scores = scores1 + scores2

# Sort all_scores in descending order: sorted_scores
sorted_scores = sorted(all_scores, reverse=True)

# Print out sorted_scores
print(sorted_scores)

[92, 88, 78, 67, 45]


## Methods
- Methods are the functions which belong to python objects.
### String Methods
- String also comes with bunch of methods as well.

In [4]:
# String to experiment with: item
item = "backpack"

# Use upper() on item
item_up = item.upper()

# Print out item and item_up
print(item)
print(item_up)

# Print out the number of 'a's in item
print(item.count("a"))


backpack
BACKPACK
2


### Other Methods
- In addition to string, Lists, floats, booleans and integers also comeup with different useful methods.
- We can always use count() to count the number of times an element appears in a list and index() to get the index the element of a list that matches the input.

In [5]:
# Create list prices
prices = [25.50, 40.75, 30.00, 25.50, 15.25]

# Print out the index of the element 30.00
print(prices.index(30.00))

# Print out how often 25.50 appears in prices
print(prices.count(25.50))

2
2


### List Methods
- We can always use different list methods such as:
  - append() , helps to extend a list by adding element
  - reverse() , helps to reverse the order of elements
  - remove() , helps to remove the first element in a list which matches the input

In [6]:
# Create list weights
weights = [55.2, 67.8, 72.5, 60.3, 58.9]

# Use append twice to add two new weights
weights.append(80.4)
weights.append(65.7)

# Print out weights
print(weights)

# Reverse the order of the elements in weights
weights.reverse()

# Print out weights
print(weights)

[55.2, 67.8, 72.5, 60.3, 58.9, 80.4, 65.7]
[65.7, 80.4, 58.9, 60.3, 72.5, 67.8, 55.2]


## Packages in Python
- Packages are the directory of python scripts and each script has module which specifies functions, methods and types.
- There are thousands of packages and some of them are numpy, matpotlib, scikit-learn etc..
- We can install any package in python using pip install.
- Before using any package we need to first import it in our code.
  - Example: 
    - import numpy as np
    - np.array[1, 3, 5]
- Basically we use the first method for package for ease and compatibility.


In [1]:
# Import the math package
import math

# Calculate C
C = 2 * 0.57 * math.pi

# Calculate A
A = math.pi * 0.57 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 3.581415625092364
Area: 1.0207034531513237


### Selective import
- If we want to import only specific part of a package then we can make our import more selective.
  - Example: 
    - from numpy import array
    - array[1, 3, 5]

In [2]:
# Import necessary functions from the math package
from math import pi, sqrt

# Define the diameter of a circle
diameter = 1.5

# Calculate the radius
radius = diameter / 2

# Calculate the circumference
circumference = 2 * pi * radius

# Calculate the area
area = pi * radius ** 2

# Calculate the diagonal of a square with side length equal to the radius
diagonal = sqrt(2) * radius

print("Circumference: " + str(circumference))
print("Area: " + str(area))
print("Diagonal of square with side equal to radius: " + str(diagonal))

Circumference: 4.71238898038469
Area: 1.7671458676442586
Diagonal of square with side equal to radius: 1.0606601717798214


## Numpy
- Numpy stands for numeric python.
- It is an alternative to the python list in the form of array.
- It helps to perform calculations over entire arrays which is pretty fast and easy.
- Python does't know how to do the calculations with list whereas numpy knows.
- Numpy assumes only to have same datatype within an array to perform all these calculations and if not so it converts all to string.
  - Example:
    - np.array([1, "hello", True])  -> converts all to string
- So we can say numpy array is also a new kind of python type like int, float etc.. and thus it comes with its own methods.


In [4]:
# Import the numpy package as np
import numpy as np

# Weights of athletes in kilograms
weights = [75, 82, 90, 78, 85, 88, 92, 80]

# Create a numpy array from weights: np_weights
np_weights = np.array(weights)

# Print out type of np_weights
print(type(np_weights))

<class 'numpy.ndarray'>


In [7]:
# Import numpy
import numpy as np

weight_lbs = [140, 233, 123, 211, 134]
# Create a numpy array from weight_lbs: np_weight_lbs
np_weight_lbs = np.array(weight_lbs)

# Print out np_weight_lbs
print(np_weight_lbs)

# Convert np_weight_lbs to kg: np_weight_kg
np_weight_kg = np_weight_lbs * 0.453592

# Print np_weight_kg
print(np_weight_kg)

[140 233 123 211 134]
[ 63.50288  105.686936  55.791816  95.707912  60.781328]


- Arithmetic operators have different meanings for python list and numpy.

In [8]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

### Arrays subsetting
- Subsetting list and array is same using square brackets.

In [11]:
import numpy as np

temperature_c = [45, 59, 12, 33, 23]
humidity_percentage = [ 12, 33, 55, 42, 65]
# Create numpy arrays from data
np_temperature_c = np.array(temperature_c)
np_humidity_percentage = np.array(humidity_percentage)

# Print out the temperature at index 4
print(np_temperature_c[4])

# Print out sub-array of np_humidity_percentage: index 2 up to and including index 4
print(np_humidity_percentage[2:5])

23
[55 42 65]


### Types of numpy arrays

In [1]:
import numpy as np
np_height = np.array([133, 158, 145, 133])
print(type(np_height))

<class 'numpy.ndarray'>


- Here nd stands for n dimensional array.
### 2D numpy arrays

In [6]:
import numpy as np
np_height = np.array([[133, 158, 145, 133], [135, 152, 145, 133]])
print(type(np_height))
np_height.shape

<class 'numpy.ndarray'>


(2, 4)

- Here above array has two rows and four columns.
- Also we can see shape is an attribute and calling an attribute is different from method as it donot use round brackets.
- We can also think numpy 2d arrays as an improved list of lists.
### Subsetting 2d arrays
- We can always subset 2d arrays as follows:

In [8]:
import numpy as np
np_height = np.array([[133, 158, 145, 133], [135, 152, 145, 133]])
print(np_height[0][2])  #[row] [column]

145


In [10]:
import numpy as np
np_height = np.array([[133, 158, 145, 133], [135, 152, 145, 133]])
print(np_height[0, 2])  #[row, column]

145


- Suppose We want both rows so we proceed as below:

In [17]:
np_height = np.array([[133, 158, 145, 133], [135, 152, 145, 133]])
print(np_height[: , 1:3])  #[start_row:end_row , index slicing in row using :]
print("\n")
print(np_height[0:2 , 1:3])

[[158 145]
 [152 145]]


[[158 145]
 [152 145]]


In [19]:
np_height = np.array([[133, 158, 145, 133], [135, 152, 145, 133]])
print(np_height[1 , :])  #this gives us the entire second row

[135 152 145 133]


### Exercise

In [20]:
import numpy as np

# Data representing heights (cm) and weights (kg) of students
students = [[165, 55.2],
            [170, 60.5],
            [175, 68.3],
            [160, 50.1]]

# Create a 2D numpy array from students: np_students
np_students = np.array(students)

# Print out the type of np_students
print(type(np_students))

# Print out the shape of np_students
print(np_students.shape)

<class 'numpy.ndarray'>
(4, 2)


In [21]:
import numpy as np

# Data representing age and salary of employees
employees = [[25, 50000],
             [30, 60000],
             [35, 75000],
             [28, 55000]]

# Create a 2D numpy array from employees: np_employees
np_employees = np.array(employees)

# Print out the shape of np_employees
print(np_employees.shape)

(4, 2)


In [23]:
import numpy as np

# Data representing age and salary of employees
employees = np.array([[25, 50000],
                      [30, 60000],
                      [35, 75000],
                      [28, 55000]])

# Print out the 3rd row of employees (assuming larger dataset)
print(employees[2, :])

# Select the entire second column of employees: np_salaries
np_salaries = employees[ : , 1 ]

# Print out age of the 2nd employee
print(employees[1, 0])

[   35 75000]
30


In [27]:
import numpy as np

# Data representing age, salary, and experience of employees
employees = np.array([[25, 50000, 2],
                      [30, 60000, 5],
                      [35, 75000, 8],
                      [28, 55000, 3]])

bonus_update = np.array([1, 10000, 1])
# Print out addition of employees and bonus_update
print(employees + bonus_update)

# Create numpy array: adjustment_factors
adjustment_factors = np.array([1, 1.1, 0.5])  # No change to age, 10% salary increase, half experience

# Print out product of employees and adjustment_factors
print(employees * adjustment_factors)

[[   26 60000     3]
 [   31 70000     6]
 [   36 85000     9]
 [   29 65000     4]]
[[2.50e+01 5.50e+04 1.00e+00]
 [3.00e+01 6.60e+04 2.50e+00]
 [3.50e+01 8.25e+04 4.00e+00]
 [2.80e+01 6.05e+04 1.50e+00]]


### Basic statistics using numpy

In [30]:
students = np.array([[165, 55.2],
            [170, 60.5],
            [175, 68.3],
            [160, 50.1]])
print(np.mean(students[:, 0]))
print(np.median(students[:, 0]))

167.5
167.5


- Apart from mean and median we can also use corrcoef for correlation and std for standard deviation.

In [35]:
print(np.corrcoef(students[:, 0], students[:, 1])) # checks if height and weight are correlated
print(np.std(students[:, 0]))  #calculates standard deviation

[[1.         0.99423367]
 [0.99423367 1.        ]]
5.5901699437494745


- Numpy enforces speed as it performs calculations only one datatype
- We can simulate or generate data using numpy function such as numpy.random.normal()
  - Arguments for it are distribution mean, distribution SD and number of samples.

In [38]:
height = np.round(np.random.normal(1.75, 0.2, 100), 2)  #generates samples
weight = np.round(np.random.normal(60.34, 15, 100), 2)
np_city = np.column_stack((height, weight))  #pastes height and weight together
#print(np_city)

### Exercise

In [39]:
# Create np_ages from np_employees
np_ages = np.array(np_employees[:, 0])

# Print out the mean of np_ages
print(np.mean(np_ages))

# Print out the median of np_ages
print(np.median(np_ages))

29.5
29.0


In [40]:

# Calculate the average age of employees
avg_age = np.mean(np_employees[:, 0])
print("Average Age: " + str(avg_age))

# Print median age
med_age = np.median(np_employees[:, 0])
print("Median Age: " + str(med_age))

# Print out the standard deviation of age
stddev_age = np.std(np_employees[:, 0])
print("Standard Deviation of Age: " + str(stddev_age))

# Print out correlation between age and salary
corr_age_salary = np.corrcoef(np_employees[:, 0], np_employees[:, 1])
print("Correlation (Age vs Salary): " + str(corr_age_salary))

Average Age: 29.5
Median Age: 29.0
Standard Deviation of Age: 3.640054944640259
Correlation (Age vs Salary): [[1.         0.99120118]
 [0.99120118 1.        ]]
